---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  vars:
    vector_use_systemd: false
  gather_facts: true
  become: true
  remote_user: root
  roles:
    - role: vector-role