---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Remove podman containers
      containers.podman.podman_container:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"