[tox]
minversion = 4.0
skipsdist = true
envlist = molecule
toxworkdir = /tmp/.tox

[testenv:molecule]
basepython = python3.10
passenv = *
deps =
  -r tox-requirements.txt
commands =
  ansible-galaxy collection install -r requirements.yml
  molecule test -s podman-lite --destroy always